spring:
  # DataSource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  # H2 Config
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(kXLCvWUqP4zjIdO9UdUqHoW8JWx6QhmGL8xDHjTonZ8=)
            client-secret: ENC(EL3u3ItlXuIqc67Y8J+9rDJFEHYFbDS9TmJysdQ5/kRXVCRe7iXpLsp9p663LSYRIjmMoUrhxIg=)

logging:
  level:
    org.springframework.boot.context.properties.bind: DEBUG

github:
  bot:
    token : ENC(GMq606IESQVXqQYSWofVPCAmIRbVKm9KkaskpVEm9msrk1Dod8YO2GrfDzdpAbe7uqAHA01F6o0=)
    username : calafs-review-bot