spring:
  # DataSource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL
    username: sa
    password:
  # H2 Config
  h2:
    console:
      enabled: true
      path: /h2-console
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ENC(kXLCvWUqP4zjIdO9UdUqHoW8JWx6QhmGL8xDHjTonZ8=)
            client-secret: ENC(EL3u3ItlXuIqc67Y8J+9rDJFEHYFbDS9TmJysdQ5/kRXVCRe7iXpLsp9p663LSYRIjmMoUrhxIg=)

logging:
  level:
    org.springframework.boot.context.properties.bind: DEBUG

github:
  bot:
    token : ENC(EU9DJ7Z/uOME/yWzJBHqRU8IiG80nmmkmvFjq2nB7QPOPMcwOFy9zTuvlPqpTpKLPLcm2Up6Xv8=)
    username : calafs-review-bot

jwt :
  secret : ENC(bNUMLg/f/WhYAclC/S73b5so4MHF8gSA26o5MhWS5LkM2RiM0932q68gjgmbbNXyid8qY30BXOc5Tb8zY4TpiIeBd+CB/Be2oOxRAKu9LfizpxqSId5k8CwR0DdwS4GR)

encrypt:
  key: ENC(3ta1LwTz9dnxRSrgRdiySXxcg8AqZZHcE4ipbi9+nVjYc70YUMe93h6OQ8E5YdcQqpIVp9VpVWKCXrjEHQensbb1Sljx9SrT)
  salt: ENC(vGlVN8XIx1jQGwFcI9l1vT5vgY3mkrRIVxtFPD0kApA5XREF/+cYe0MB+FPR3Iz1)